import { ArrowRight, Bot, CheckCircle2, CircleDot, GitBranch, LockKeyhole, MemoryStick, Network, ShieldCheck, Sparkles, Trash2 } from "lucide-react";
import type { OSBootstrap } from "../types";
import { EmptyState, PageHeading, StatusPill } from "../components/ProductComponents";
import { formatAgent } from "../utils";

export function RequestsPage({ data, onNavigate }: { data: OSBootstrap; onNavigate: (path: string) => void }) {
  return <div className="standard-page"><PageHeading eyebrow="Task workspaces" title="Your requests" copy="Each request has a separate conversation, intent post, candidate rooms, evidence, and decision boundary." />{data.tasks.length ? <div className="request-list">{data.tasks.map((task) => <button key={task.task_id} onClick={() => onNavigate(`/requests/${task.task_id}`)}><span className="request-icon"><CircleDot size={17} /></span><div><strong>{task.title}</strong><p>{task.goal}</p><small>{data.rooms.filter((room) => room.task_id === task.task_id).length} rooms · {data.candidateAssessments.filter((item) => item.task_id === task.task_id).length} candidates</small></div><StatusPill status={task.status} /><ArrowRight size={15} /></button>)}</div> : <EmptyState title="No requests yet" body="Start in My Agent and tell Qi what outcome you want." />}</div>;
}

export function MatchesPage({ data, onNavigate }: { data: OSBootstrap; onNavigate: (path: string) => void }) {
  const matches = data.demoState.matches;
  return <div className="standard-page"><PageHeading eyebrow="Human-approved outcomes" title="Matches" copy="A match appears only after both posts, the exact proposal version, the active hold, and your explicit approval are committed." />{matches.length ? <div className="match-list">{matches.map((match, index) => <article key={String(match.matchId || index)}><span className="match-check"><CheckCircle2 size={25} /></span><div><span>Committed match</span><h2>You’re matched with {formatAgent(String(match.candidateAgentId || "maya-agent")).replace(" Agent", "")}</h2><p>Both intent posts closed · other negotiations released · shared coordination unlocked.</p><div><ShieldCheck size={14} /> Refresh-safe exact-effect commitment</div></div><button onClick={() => { const room = data.rooms.find((item) => item.status === "COMPLETED"); if (room) onNavigate(`/rooms/${room.room_id}`); }}>Open shared room <ArrowRight size={14} /></button></article>)}</div> : <EmptyState title="No committed matches" body="Qi can negotiate, but only your exact-effect approval creates a match." />}</div>;
}

export function NetworkPage({ data }: { data: OSBootstrap }) {
  const activeAgents = new Set(data.demoState.messages.flatMap((message) => [String(message.fromAgentId || ""), String(message.toAgentId || "")]));
  const nodes = [
    { id: "qi-agent", title: "Qi Agent", role: "Your persistent Personal Agent", x: 50, y: 50 },
    { id: "alice-agent", title: "Alice Agent", role: "Trusted introducer", x: 22, y: 20 },
    { id: "maya-agent", title: "Maya Agent", role: "Intent owner", x: 78, y: 20 },
    { id: "lena-agent", title: "Lena Agent", role: "Intent owner", x: 78, y: 78 },
  ];
  return <div className="standard-page"><PageHeading eyebrow="Relationship provenance" title="Your agent network" copy="Relationships can help discovery and introductions. They never override current intent evidence or commitment authority." /><section className="network-canvas"><svg aria-hidden="true" viewBox="0 0 100 100"><line x1="50" y1="50" x2="22" y2="20" /><line x1="22" y1="20" x2="78" y2="20" /><line x1="50" y1="50" x2="78" y2="20" /><line x1="50" y1="50" x2="78" y2="78" /></svg>{nodes.map((node) => <article className={`network-person ${activeAgents.has(node.id) || node.id === "qi-agent" ? "active" : ""}`} style={{ left: `${node.x}%`, top: `${node.y}%` }} key={node.id}><span><Bot size={18} /></span><div><strong>{node.title}</strong><small>{node.role}</small></div><i /></article>)}</section><div className="network-explanation"><GitBranch size={17} /><span><strong>Alice → Maya is an introduction path</strong><small>Peer claims remain non-authoritative until verified or negotiated inside a scoped room.</small></span></div></div>;
}

export function MemoryPage({ data, onAction }: { data: OSBootstrap; onAction: (id: string, action: string) => void }) {
  return <div className="standard-page"><PageHeading eyebrow="Reviewable personal context" title="Memory" copy="Qi learns only from committed outcomes. Every inference remains scoped, editable, restrictable, and deletable." /><div className="memory-list"><article className="memory-card foundation"><Network size={19} /><div><span>Trusted foundation</span><h2>Alice is a provenance-backed coordination relationship</h2><p>Used to request an introduction, never as proof of roommate compatibility.</p></div><StatusPill status="VERIFIED" /></article>{data.demoState.memories.length ? data.demoState.memories.map((memory, index) => { const id = String(memory.memoryId || memory.memory_id || index); return <article className="memory-card" key={id}><MemoryStick size={19} /><div><span>Scoped inference</span><h2>{String(memory.content || memory.summary || "You accepted partial date coverage to preserve quietness")}</h2><p>Source: committed match · Scope: hotel sharing · Confidence remains bounded.</p><footer><button onClick={() => onAction(id, "CONFIRM")}><CheckCircle2 size={14} /> Confirm</button><button onClick={() => onAction(id, "RESTRICT_SCOPE")}><LockKeyhole size={14} /> Restrict</button><button onClick={() => onAction(id, "DELETE")}><Trash2 size={14} /> Delete</button></footer></div><StatusPill status={String(memory.status || "REVIEW")} /></article>; }) : <EmptyState title="No learned preferences yet" body="Uncommitted agent chat and peer claims never write durable memory." />}</div></div>;
}

export function AuditPage({ data }: { data: OSBootstrap }) {
  const events = [...data.demoState.messages.map((item) => ({ type: String(item.speechAct || "A2A message"), summary: String(item.naturalLanguage || ""), meta: `${String(item.fromAgentId)} → ${String(item.toAgentId)} · ${String(item.pairSessionId)}` })), ...data.demoState.turns.map((item) => ({ type: String(item.selectedTool || "Agent tool"), summary: String(item.stateTransition || "Completed"), meta: `${String(item.turnId)} · ${String(item.latencyMs || 0)}ms` }))];
  return <div className="standard-page"><PageHeading eyebrow="Developer proof" title="Authoritative audit" copy={`Live ${data.demoState.exactModelId} · Google ADK · authenticated A2A · server-side authority enforcement`} /><div className="proof-strip"><span><Sparkles size={15} /> Gemini model-selected strategy</span><span><Bot size={15} /> Google ADK typed agents</span><span><ShieldCheck size={15} /> Server-enforced privacy</span><span><LockKeyhole size={15} /> Exact-effect approval</span></div><section className="audit-feed">{events.length ? events.map((event, index) => <article key={`${event.type}-${index}`}><span>{index + 1}</span><div><header><strong>{event.type.replaceAll("_", " ")}</strong><StatusPill status="VERIFIED" /></header><p>{event.summary}</p><small>{event.meta}</small></div></article>) : <EmptyState title="No run evidence yet" body="Publish a request to produce model, tool, A2A, policy, approval, and commitment evidence." />}</section><div className="truth-note"><ShieldCheck size={16} /><span><strong>Implementation truth</strong><small>Peer humans are synthetic: {String(data.implementationTruth.peerHumansAreSynthetic)} · Dynamic internal workers implemented: {String(data.implementationTruth.dynamicWorkersImplemented)}</small></span></div></div>;
}
