"""Typed contracts shared by PairPilot services."""

from pairpilot_schemas.agent_messages import (
    A2AMessageEnvelope,
    A2AProposal,
    Claim,
    ClaimSource,
    PeerClaimDraft,
    PeerDecision,
    SpeechAct,
)
from pairpilot_schemas.domain import (
    Approval,
    Availability,
    EvidenceKind,
    EvidenceRecord,
    FieldSource,
    Hold,
    IntentPost,
    IntentPrivateContext,
    IntentPublicConstraints,
    IntentStatus,
    Match,
    MemoryRecord,
    NegotiationBoundaries,
    Proposal,
    RelationshipUpdate,
    canonical_intent_pair,
)
from pairpilot_schemas.intent_draft import (
    AgentOnlyDraft,
    DraftFieldProvenance,
    IntentDraft,
)
from pairpilot_schemas.introduction import IntroductionDecision

__all__ = [
    "A2AMessageEnvelope",
    "A2AProposal",
    "AgentOnlyDraft",
    "DraftFieldProvenance",
    "Approval",
    "Availability",
    "Claim",
    "ClaimSource",
    "EvidenceKind",
    "EvidenceRecord",
    "FieldSource",
    "Hold",
    "IntentPost",
    "IntentPrivateContext",
    "IntentPublicConstraints",
    "IntentStatus",
    "IntentDraft",
    "IntroductionDecision",
    "Match",
    "MemoryRecord",
    "NegotiationBoundaries",
    "PeerClaimDraft",
    "PeerDecision",
    "Proposal",
    "RelationshipUpdate",
    "SpeechAct",
    "canonical_intent_pair",
]
