"""Shared structured result for an independent introduction decision."""

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class IntroductionDecision(BaseModel):
    """Decision generated by the relationship owner, never by the orchestrator."""

    model_config = ConfigDict(extra="forbid")

    decision: Literal["OFFER_INTRODUCTION", "DECLINE_INTRODUCTION"]
    natural_language: str = Field(min_length=1, max_length=800)
    reason: str = Field(min_length=1, max_length=500)
    confidence: float = Field(ge=0.0, le=1.0)

